### Import Packages

In [19]:
from selenium import webdriver
import pandas as pd

### Open Link

In [14]:
driver=webdriver.Chrome('C:\webdrivers\chromedriver.exe')

driver.get('https://pokemondb.net/pokedex/all')
driver.maximize_window()

In [15]:
#Privacy Policy
button=driver.find_element_by_class_name('gdpr-accept')
try:
    button.click()
except:
    pass

### Create Locators

In [16]:
#name
pokemon_name=driver.find_elements_by_xpath('//tbody/tr/td[2]')

#type
pokemon_type=driver.find_elements_by_xpath('//tbody/tr/td[3]')

#total
pokemon_total=driver.find_elements_by_xpath('//tbody/tr/td[4]')

#hp
pokemon_hp=driver.find_elements_by_xpath('//tbody/tr/td[5]')

#attack
pokemon_attack=driver.find_elements_by_xpath('//tbody/tr/td[6]')

#defense
pokemon_defense=driver.find_elements_by_xpath('//tbody/tr/td[7]')

#sp.attack
pokemon_sp_attack=driver.find_elements_by_xpath('//tbody/tr/td[8]')

#sp.def
pokemon_sp_def=driver.find_elements_by_xpath('//tbody/tr/td[9]')

#speed
pokemon_speed=driver.find_elements_by_xpath('//tbody/tr/td[10]')

### Empty List

In [17]:
pokemon_results=[]

### Dictionary

In [18]:
for i in range(len(pokemon_name)):
    pokemon_dictionary={'Name':pokemon_name[i].text,
                        'Type':pokemon_type[i].text,
                        'Total':pokemon_total[i].text,
                        'HP':pokemon_hp[i].text,
                       'Attack':pokemon_attack[i].text,
                       'Defense':pokemon_attack[i].text,
                       'Sp.Attack':pokemon_sp_attack[i].text,
                       'Sp.Defense':pokemon_sp_def[i].text,
                       'Speed':pokemon_speed[i].text}
    pokemon_results.append(pokemon_dictionary)

### Create Dataframe

In [20]:
dataframe_pokemon=pd.DataFrame(pokemon_results)

In [21]:
dataframe_pokemon

,Name,Type,Total,HP,Attack,Defense,Sp.Attack,Sp.Defense,Speed
0,Bulbasaur,GRASS\nPOISON,318,45,49,49,65,65,45
1,Ivysaur,GRASS\nPOISON,405,60,62,62,80,80,60
2,Venusaur,GRASS\nPOISON,525,80,82,82,100,100,80
3,Venusaur\nMega Venusaur,GRASS\nPOISON,625,80,100,100,122,120,80
4,Charmander,FIRE,309,39,52,52,60,50,65
...,...,...,...,...,...,...,...,...,...
1040,Glastrier,ICE,580,100,145,145,65,110,30
1041,Spectrier,GHOST,580,100,65,65,145,80,130
1042,Calyrex,PSYCHIC\nGRASS,500,100,80,80,80,80,80
1043,Calyrex\nIce Rider,PSYCHIC\nICE,680,100,165,165,85,130,50
1044,Calyrex\nShadow Rider,PSYCHIC\nGHOST,680,100,85,85,165,100,150

### Replace Unnecessary Characters

In [22]:
#replace \n with a comma
dataframe_pokemon['Type']=dataframe_pokemon['Type'].apply(lambda x:x.replace('\n',','))

In [24]:
#replace \n with a /
dataframe_pokemon['Name']=dataframe_pokemon['Name'].apply(lambda x:x.replace('\n','/'))

In [25]:
#updated dataframe
dataframe_pokemon

,Name,Type,Total,HP,Attack,Defense,Sp.Attack,Sp.Defense,Speed
0,Bulbasaur,"GRASS,POISON",318,45,49,49,65,65,45
1,Ivysaur,"GRASS,POISON",405,60,62,62,80,80,60
2,Venusaur,"GRASS,POISON",525,80,82,82,100,100,80
3,Venusaur/Mega Venusaur,"GRASS,POISON",625,80,100,100,122,120,80
4,Charmander,FIRE,309,39,52,52,60,50,65
...,...,...,...,...,...,...,...,...,...
1040,Glastrier,ICE,580,100,145,145,65,110,30
1041,Spectrier,GHOST,580,100,65,65,145,80,130
1042,Calyrex,"PSYCHIC,GRASS",500,100,80,80,80,80,80
1043,Calyrex/Ice Rider,"PSYCHIC,ICE",680,100,165,165,85,130,50
1044,Calyrex/Shadow Rider,"PSYCHIC,GHOST",680,100,85,85,165,100,150

### Dataframe to Excel

In [26]:
dataframe_pokemon.to_excel('pokemon_database_cleaned.xlsx', index=False)